## Data root
data_root: !join [workspace_results/shared/monik/]
filename: test_reconSoS.npz
# data config
subject_name: &subject_name 11_knee
slice: &slice 10 # 20
fe_steps: 536
n_slices: 67
nc_recon: &nc_recon 27
#coil_select: [0] #[2,3,4,5,6,7]1
coil_select: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26] #[2,3,4,5,6,7]
## recon config
nc: *nc_recon

num_steps: 1000
## Dataloader
dataset:
  module: datasets.radialSoS_sorted
  name: RadialSoSDataset
  nav_min: 0
  nav_max: 0.0
  nav_drift: True
  fe_crop: 1       # crop the FE range (resolution is decreased)
  acc_factor: 1     # cut spokes
  scale_coils: False     # cut spokes

### Reference method
xdgrasp:
  beta: [0, 0.1]
  nMS: 1
  method: equal_spokes_no # rel_displacement

encoding:
  type: STIFF
  sigma: 1
  spat_feat_perc: 1.
  pi_factor: True
## Models