## Data root
data_root: !join [workspace_results/shared/xcat/]
filename: test_reconSoS.npz
# data config
subject_name: &subject_name _phantom_2echo_6coil_0.5FS
slice: &slice 20
fe_steps: 448
n_slices: 84
nc_recon: &nc_recon 1
coil_select: [0,1,2,3,4,5]
#coil_select: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25] #[2,3,4,5,6,7]
## recon config
nc: *nc_recon